import hou


class ATTRIBUTE_TYPE:
    INT = 0
    INT_LIST = 1
    FLOAT = 2
    FLOAT_LIST = 3
    STRING = 4
    STRING_LIST = 5


ATTRIBUTE_FUNCTION = dict()
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.INT] = hou.Point.intAttribValue
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.INT_LIST] = hou.Point.intListAttribValue
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.FLOAT] = hou.Point.floatAttribValue
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.FLOAT_LIST] = hou.Point.floatListAttribValue
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.STRING] = hou.Point.stringAttribValue
ATTRIBUTE_FUNCTION[ATTRIBUTE_TYPE.STRING_LIST] = hou.Point.stringListAttribValue
